// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifndef FCC_BYTE_TYPE_DEFINED
typedef unsigned char BYTE;
#define FCC_BYTE_TYPE_DEFINED 1
#endif

enum {
  FCC_MAX_IDENTIFIER_LENGTH = 128,
  FCC_MAX_FUNCTION_PARAMETERS = 128,
  FCC_MAX_TYPEDEF_NAME_LENGTH = 128,
  FCC_MAX_LABEL_NAME_LENGTH = 128,
  FCC_MAX_DIAG_MESSAGE_LENGTH = 256,
  FCC_MAX_INCLUDE_DIRECTORIES = 32,
  FCC_MAX_PATH_LENGTH = 512,
  FCC_MAX_PARSE_DEPTH = 256,
  FCC_MAX_PREPROCESS_DEPTH = 64,
  FCC_MAX_PREPROCESS_CONDITIONAL_DEPTH = 64,
  FCC_MAX_SEMA_DEPTH = 256,
  FCC_MAX_CODEGEN_DEPTH = 256,
  FCC_MAX_WINDOWS_X64_REGISTER_ARGUMENTS = 4
};
