// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <stddef.h>
#include <stdio.h>

#include "fcc/source.h"

typedef enum FccTokenKind {
  FCC_TOKEN_INVALID = 0,
  FCC_TOKEN_END_OF_FILE,
  FCC_TOKEN_IDENTIFIER,
  FCC_TOKEN_INTEGER_LITERAL,
  FCC_TOKEN_STRING_LITERAL,
  FCC_TOKEN_CHAR_LITERAL,
  FCC_TOKEN_KW_INT,
  FCC_TOKEN_KW_VOID,
  FCC_TOKEN_KW_CHAR,
  FCC_TOKEN_KW_SIGNED,
  FCC_TOKEN_KW_UNSIGNED,
  FCC_TOKEN_KW_SHORT,
  FCC_TOKEN_KW_LONG,
  FCC_TOKEN_KW_BOOL,
  FCC_TOKEN_KW_STRUCT,
  FCC_TOKEN_KW_UNION,
  FCC_TOKEN_KW_ENUM,
  FCC_TOKEN_KW_TYPEDEF,
  FCC_TOKEN_KW_RETURN,
  FCC_TOKEN_KW_IF,
  FCC_TOKEN_KW_ELSE,
  FCC_TOKEN_KW_WHILE,
  FCC_TOKEN_KW_DO,
  FCC_TOKEN_KW_FOR,
  FCC_TOKEN_KW_SWITCH,
  FCC_TOKEN_KW_CASE,
  FCC_TOKEN_KW_DEFAULT,
  FCC_TOKEN_KW_GOTO,
  FCC_TOKEN_KW_BREAK,
  FCC_TOKEN_KW_CONTINUE,
  FCC_TOKEN_KW_STATIC,
  FCC_TOKEN_KW_EXTERN,
  FCC_TOKEN_KW_CONST,
  FCC_TOKEN_KW_SIZEOF,
  FCC_TOKEN_KW_ALIGNOF,
  FCC_TOKEN_KW_STATIC_ASSERT,
  FCC_TOKEN_LPAREN,
  FCC_TOKEN_RPAREN,
  FCC_TOKEN_LBRACE,
  FCC_TOKEN_RBRACE,
  FCC_TOKEN_LBRACKET,
  FCC_TOKEN_RBRACKET,
  FCC_TOKEN_SEMICOLON,
  FCC_TOKEN_COMMA,
  FCC_TOKEN_DOT,
  FCC_TOKEN_ELLIPSIS,
  FCC_TOKEN_ARROW,
  FCC_TOKEN_QUESTION,
  FCC_TOKEN_COLON,
  FCC_TOKEN_PLUS,
  FCC_TOKEN_MINUS,
  FCC_TOKEN_STAR,
  FCC_TOKEN_SLASH,
  FCC_TOKEN_PERCENT,
  FCC_TOKEN_ASSIGN,
  FCC_TOKEN_PLUS_ASSIGN,
  FCC_TOKEN_MINUS_ASSIGN,
  FCC_TOKEN_STAR_ASSIGN,
  FCC_TOKEN_SLASH_ASSIGN,
  FCC_TOKEN_PERCENT_ASSIGN,
  FCC_TOKEN_BITWISE_AND_ASSIGN,
  FCC_TOKEN_BITWISE_OR_ASSIGN,
  FCC_TOKEN_BITWISE_XOR_ASSIGN,
  FCC_TOKEN_EQUAL,
  FCC_TOKEN_NOT_EQUAL,
  FCC_TOKEN_LESS,
  FCC_TOKEN_LESS_EQUAL,
  FCC_TOKEN_GREATER,
  FCC_TOKEN_GREATER_EQUAL,
  FCC_TOKEN_LEFT_SHIFT_ASSIGN,
  FCC_TOKEN_RIGHT_SHIFT_ASSIGN,
  FCC_TOKEN_LOGICAL_AND,
  FCC_TOKEN_LOGICAL_OR,
  FCC_TOKEN_LOGICAL_NOT,
  FCC_TOKEN_BITWISE_AND,
  FCC_TOKEN_BITWISE_OR,
  FCC_TOKEN_BITWISE_XOR,
  FCC_TOKEN_BITWISE_NOT,
  FCC_TOKEN_LEFT_SHIFT,
  FCC_TOKEN_RIGHT_SHIFT,
  FCC_TOKEN_INCREMENT,
  FCC_TOKEN_DECREMENT
} FccTokenKind;

typedef struct FccToken {
  FccTokenKind kind;
  FccSourceSpan span;
  size_t text_length;
  const char* interned_text;
} FccToken;

const char* fcc_token_kind_name(FccTokenKind kind);

void fcc_token_dump(FILE* stream, const FccToken* token);

void fcc_token_dump_source(FILE* stream, const FccToken* token, const FccSourceFile* source_file);
